repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        files: poc/.*
      - id: end-of-file-fixer
        files: poc/.*
      - id: check-yaml
        files: poc/.*
      - id: check-added-large-files
        files: poc/.*
