repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        files: poc/.*
      - id: end-of-file-fixer
        files: poc/.*
      - id: check-yaml
        files: poc/.*
      - id: check-added-large-files
        files: poc/.*
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
        files: poc/.*
      - id: go-imports
        files: poc/.*
      - id: no-go-testing
        files: poc/.*
      - id: golangci-lint
        files: poc/.*
      - id: go-unit-tests
        files: poc/.*
