# permissions for end users to edit engineers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: engineer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: poc
    app.kubernetes.io/part-of: poc
    app.kubernetes.io/managed-by: kustomize
  name: engineer-editor-role
rules:
- apiGroups:
  - kiratech.tutorial.status
  resources:
  - engineers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kiratech.tutorial.status
  resources:
  - engineers/status
  verbs:
  - get
