---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kiratech.tutorial.status
  resources:
  - engineers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kiratech.tutorial.status
  resources:
  - engineers/finalizers
  verbs:
  - update
- apiGroups:
  - kiratech.tutorial.status
  resources:
  - engineers/status
  verbs:
  - get
  - patch
  - update
